language: java

jdk:
- openjdk8

before_script:
  - mvn install -DskipTests=true -B -V

script:
  - mvn test -B

after_success:
  - mvn -DrepoToken=$COVERALLS_REPO_TOKEN clean test jacoco:report coveralls:report

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: v1-code

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
    - apisupport@zenvia.com
