language: java

jdk:
- openjdk8

before_script:
  - mvn install -DskipTests=true -B -V

script:
  - mvn test -B

after_success:
  - mvn -DrepoToken=$COVERALLS_REPO_TOKEN clean cobertura:cobertura coveralls:report

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
    - apisupport@zenvia.com
